Auction Beta Version/Nilam/Controllers/SearchProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using dbLayer;
using System.Data.Entity;

namespace Nilam.Controllers
{
    public class SearchProductController : Controller
    {

        AuctionEntities searchProduct = new AuctionEntities();
        // GET: SearchProduct
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult searchProducts(string SearchBy, string search, string productID)
        {
            ViewBag.categories = new SelectList(searchProduct.productTables, "productID", "productCategory");
            DateTime currentDataAndTime = DateTime.Now;
            string userNameFromSession1 = Session["userName"].ToString();
            if (SearchBy == "Category")
            {
                return View(searchProduct.productTables.Where(x => x.productCategory.StartsWith(search) && x.uploader != userNameFromSession1 && x.endDate> currentDataAndTime && x.startDate <= currentDataAndTime || search == null).ToList());
            }
            else
                return View(searchProduct.productTables.Where(x => x.productName.StartsWith(search) && x.uploader != userNameFromSession1 && x.endDate > currentDataAndTime && x.startDate <= currentDataAndTime || search == null).ToList());


            //if (!string.IsNullOrEmpty(productID))
            //{
            //    int pID = Convert.ToInt32(productID);
            //    return View(searchProduct.productTables.Where(x => x.productID == pID));
            //}

            //return View(searchProduct.productTables.Where(x => x.productName.StartsWith(search) || search == null).ToList());

        }

        // bid from search list

        //update bid
        public ActionResult BidFromSearch(int productID = 1)
        {
            return View(searchProduct.productTables.Find(productID));
        }

        [HttpPost]
        public ActionResult BidFromSearch(productTable upd)
        {
            //upd.biddedPrice = 69;
            //ViewBag.shohan = new SelectList(acForBid.productTables, "productID", "basePrice");

            searchProduct.Entry(upd).State = EntityState.Modified;
            searchProduct.SaveChanges();
            return RedirectToAction("ShowBidListForUser", "Product");
            
        }

    }
}

Auction Beta Version/Nilam/Views/SearchProduct/BidFromSearch.cshtml
@model dbLayer.productTable

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Place Bid</title>

    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>

</head>
<body>
    <div class="container">
        <div class="col-md-11">

        </div>

        <div class="col-md-1">
            <form method="post" id="ForgotPassword" action="~/Account/Logout">
                <button type="submit" class="btn btn-danger">Log Out</button>
            </form>
        </div>
    </div>
    <div class="container">
        <h2 class="well text-center">Place your Bid</h2>
    </div>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @*@Html.LabelFor(model => model.productID, htmlAttributes: new { @class = "control-label col-md-2" })*@
                <div class="col-md-10">
                    @Html.EditorFor(model => model.productID, new { htmlAttributes = new { @class = "form-control", style = "display:none;" } })
                    @Html.ValidationMessageFor(model => model.productID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @*@Html.LabelFor(model => model.productName, htmlAttributes: new { @class = "control-label col-md-2" })*@
                <div class="col-md-10">
                    @Html.EditorFor(model => model.productName, new { htmlAttributes = new { @class = "form-control", style = "display:none;" } })
                    @Html.ValidationMessageFor(model => model.productName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @*@Html.LabelFor(model => model.productInfo, htmlAttributes: new { @class = "control-label col-md-2" })*@
                <div class="col-md-10">
                    @Html.EditorFor(model => model.productInfo, new { htmlAttributes = new { @class = "form-control", style = "display:none;" } })
                    @Html.ValidationMessageFor(model => model.productInfo, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @*@Html.LabelFor(model => model.basePrice, htmlAttributes: new { @class = "control-label col-md-2" })*@
                <div class="col-md-10">
                    @Html.EditorFor(model => model.basePrice, new { htmlAttributes = new { @class = "form-control", style = "display:none;" } })
                    @Html.ValidationMessageFor(model => model.basePrice, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @*@Html.LabelFor(model => model.startDate, htmlAttributes: new { @class = "control-label col-md-2" })*@
                <div class="col-md-10">
                    @Html.EditorFor(model => model.startDate, new { htmlAttributes = new { @class = "form-control", style = "display:none;" } })
                    @Html.ValidationMessageFor(model => model.startDate, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @*@Html.LabelFor(model => model.endDate, htmlAttributes: new { @class = "control-label col-md-2" })*@
                <div class="col-md-10">
                    @Html.EditorFor(model => model.endDate, new { htmlAttributes = new { @class = "form-control", style = "display:none;" } })
                    @Html.ValidationMessageFor(model => model.endDate, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.biddedPrice, htmlAttributes: new { @class = "control-label col-md-2" })
                @*<div class="col-md-10">
                        @Html.EditorFor(model => model.biddedPrice, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.biddedPrice, "", new { @class = "text-danger" })
                    </div>*@
                <div class="col-md-10">
                    @{
                        var valueFromDB = Html.DisplayFor(model => model.biddedPrice).ToString();


                        if (valueFromDB == "")
                        {
                            var valueFromDBofBasePrice = Html.DisplayFor(model => model.basePrice).ToString();
                            int convertOFvalueFromDBofBasePrice = Convert.ToInt32(valueFromDBofBasePrice);
                            var tokenFor50 = 50 + convertOFvalueFromDBofBasePrice;
                            var tokenFor100 = 100 + convertOFvalueFromDBofBasePrice;
                            var tokenFor250 = 250 + convertOFvalueFromDBofBasePrice;
                            var tokenFor500 = 500 + convertOFvalueFromDBofBasePrice;
                            List<SelectListItem> listItems = new List<SelectListItem>();
                            listItems.Add(new SelectListItem
                            {
                                Text = "50",
                                Value = tokenFor50.ToString(),
                                Selected = true
                            });
                            listItems.Add(new SelectListItem
                            {
                                Text = "100",
                                Value = tokenFor100.ToString()
                            });
                            listItems.Add(new SelectListItem
                            {
                                Text = "250",
                                Value = tokenFor250.ToString()
                            });
                            listItems.Add(new SelectListItem
                            {
                                Text = "500",
                                Value = tokenFor500.ToString()
                            });
                            @Html.DropDownListFor(model => model.biddedPrice, listItems)
                        }



                        else
                        {
                            int convertOFvalueFromDB = Convert.ToInt32(valueFromDB);
                            var tokenFor50 = 50 + convertOFvalueFromDB;
                            var tokenFor100 = 100 + convertOFvalueFromDB;
                            var tokenFor250 = 250 + convertOFvalueFromDB;
                            var tokenFor500 = 500 + convertOFvalueFromDB;
                            List<SelectListItem> listItems = new List<SelectListItem>();
                            listItems.Add(new SelectListItem
                            {
                                Text = "50",
                                Value = tokenFor50.ToString(),
                                Selected = true
                            });
                            listItems.Add(new SelectListItem
                            {
                                Text = "100",
                                Value = tokenFor100.ToString()
                            });
                            listItems.Add(new SelectListItem
                            {
                                Text = "250",
                                Value = tokenFor250.ToString()
                            });
                            listItems.Add(new SelectListItem
                            {
                                Text = "500",
                                Value = tokenFor500.ToString()
                            });
                            @Html.DropDownListFor(model => model.biddedPrice, listItems)
                        }

                    }


                </div>
            </div>

            <div class="form-group">
                @*@Html.LabelFor(model => model.productCategory, htmlAttributes: new { @class = "control-label col-md-2" })*@
                <div class="col-md-10">
                    @Html.EditorFor(model => model.productCategory, new { htmlAttributes = new { @class = "form-control", style = "display:none;" } })
                    @Html.ValidationMessageFor(model => model.productCategory, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @*@Html.LabelFor(model => model.uploader, htmlAttributes: new { @class = "control-label col-md-2" })*@
                <div class="col-md-10">
                    @Html.EditorFor(model => model.uploader, new { htmlAttributes = new { @class = "form-control", style = "display:none;" } })
                    @Html.ValidationMessageFor(model => model.uploader, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @*@Html.LabelFor(model => model.bidder, htmlAttributes: new { @class = "control-label col-md-2" })*@
                <div class="col-md-10">
                    @Html.EditorFor(model => model.bidder, new { htmlAttributes = new { @class = "form-control", Value = Session["userName"].ToString(), style = "display:none;" } })
                    @Html.ValidationMessageFor(model => model.bidder, "", new { @class = "text-danger" })
                </div>

            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Place Bid" class="btn btn-success" />
                </div>
            </div>
        </div>
                        }

    <div class="container">
        <form method="post" id="goback" action="~/Bid/availableProducts">
            <button type="submit" class="btn btn-info"><span class="glyphicon glyphicon-arrow-left" aria-hidden="true">Go Back</span></button>
        </form>
    </div>
</body>
</html>

Auction Beta Version/Nilam/Views/SearchProduct/searchProducts.cshtml
@model IEnumerable<dbLayer.productTable>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Search Available Products</title>


    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>

</head>
<body>
    <div class="container">
        <div class="col-md-11">

        </div>

        <div class="col-md-1">
            <form method="post" id="ForgotPassword" action="~/Account/Logout">
                <button type="submit" class="btn btn-danger">Log Out</button>
            </form>
        </div>
    </div>
    <div class="container">
        <h2 class="well text-center">All Available Products</h2>
    </div>

    <div class="container text-center">
        <p>
            @using (Html.BeginForm("searchProducts", "SearchProduct", FormMethod.Get))
            {
                <b> Search By: </b>
                @Html.RadioButton("SearchBy", "Name", true)<text> Name</text>
                @*@Html.DropDownList("categories","Select Category")*@
                @Html.RadioButton("SearchBy", "Category")<text> Category</text>
                <br />
                @Html.TextBox("search") <input type="submit" value="Search" class="btn btn-primary"/>
            }
        </p>
    </div>
    <div class="container">
        <table class="table table-striped" border="1">
            <tr>
                @*<th>
                        @Html.DisplayNameFor(model => model.productID)
                    </th>*@
                <th>
                    Product Name
                </th>
                <th>
                    Product Info
                </th>
                <th>
                    Base Price
                </th>
                <th>
                    Start Date
                </th>
                <th>
                    End Date
                </th>
                <th>
                    Bidded Price
                </th>
                <th>
                    Product Category
                </th>
                <th>
                    Uploader
                </th>
                <th>
                    Bidder
                </th>
                <th>Action</th>
            </tr>

            @if (Model.Count() == 0)
            {
                <tr>
                    <td colspan="8" rowspan="5" style="color:red;">No Match Found For This Query</td>
                </tr>
            }

            else
            {

                foreach (var item in Model)
                {
                    <tr>

                        <td>
                            @Html.DisplayFor(modelItem => item.productName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.productInfo)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.basePrice)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.startDate)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.endDate)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.biddedPrice)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.productCategory)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.uploader)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.bidder)
                        </td>

                        <td>
                            @Html.ActionLink("Bid on this", "BidFromSearch", new { productID = item.productID/* id=item.PrimaryKey */ }) 

                        </td>
                    </tr>
                }
            }

        </table>
    </div>

    <div class="container">
        <form method="post" id="goback" action="~/Bid/availableProducts">
            <button type="submit" class="btn btn-info"><span class="glyphicon glyphicon-arrow-left" aria-hidden="true">Go Back Dashboard</span></button>
        </form>
    </div>
</body>
</html>